# Jekyll configuration for NakedMud Documentation
title: "NakedMud Documentation"
description: "Comprehensive documentation for NakedMud MUD library"
baseurl: ""
url: ""

# Build settings
markdown: kramdown
highlighter: rouge
theme: just-the-docs

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Just the Docs theme settings
color_scheme: light
search_enabled: true
heading_anchors: true

# Footer content
footer_content: "Copyright &copy; 2024 NakedMud Development Team."

# Aux links (top right)
aux_links:
  "GitHub Repository":
    - "//github.com/nakedmud/nakedmud"

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - _scripts/

# Additional Jekyll settings
permalink: pretty